// Définition des 63 groupes de pays et leurs modificateurs de difficulté
const COUNTRY_GROUPS = [
    // TIER S
    { id: 1, tier: 'S', multBytes: 0.5, avSpeed: 1.5, countries: ["Royaume-Uni", "États-Unis", "Estonie", "Singapour"] },
    { id: 2, tier: 'S', multBytes: 0.55, avSpeed: 1.5, countries: ["Espagne", "République de Corée", "France", "Lituanie"] },
    { id: 3, tier: 'S', multBytes: 0.6, avSpeed: 1.5, countries: ["Malaisie", "Allemagne", "Émirats Arabes Unis", "Japon"] },
    { id: 4, tier: 'S', multBytes: 0.7, avSpeed: 1.5, countries: ["Canada", "Australie", "Pays-Bas", "Finlande"] },
    // TIER A
    { id: 5, tier: 'A', multBytes: 0.8, avSpeed: 1.2, countries: ["Suède", "Danemark", "Norvège"] },
    { id: 6, tier: 'A', multBytes: 0.82, avSpeed: 1.2, countries: ["Suisse", "Israël", "Belgique"] },
    { id: 7, tier: 'A', multBytes: 0.85, avSpeed: 1.2, countries: ["Portugal", "Italie", "Autriche"] },
    { id: 8, tier: 'A', multBytes: 0.88, avSpeed: 1.2, countries: ["Pologne", "Inde", "Arabie Saoudite"] },
    { id: 9, tier: 'A', multBytes: 0.9, avSpeed: 1.2, countries: ["Qatar", "Oman", "Bahreïn"] },
    { id: 10, tier: 'A', multBytes: 0.92, avSpeed: 1.2, countries: ["Turquie", "Brésil", "Égypte"] },
    { id: 11, tier: 'A', multBytes: 0.95, avSpeed: 1.2, countries: ["Nouvelle-Zélande", "Irlande", "République Tchèque"] },
    { id: 12, tier: 'A', multBytes: 0.98, avSpeed: 1.2, countries: ["Hongrie", "Grèce", "Slovaquie"] },
    { id: 13, tier: 'A', multBytes: 1.0, avSpeed: 1.2, countries: ["Roumanie", "Bulgarie", "Croatie"] },
    { id: 14, tier: 'A', multBytes: 1.02, avSpeed: 1.2, countries: ["Chypre", "Slovénie", "Lettonie"] },
    { id: 15, tier: 'A', multBytes: 1.05, avSpeed: 1.2, countries: ["Islande", "Luxembourg", "Malte"] },
    { id: 16, tier: 'A', multBytes: 1.08, avSpeed: 1.2, countries: ["Chili", "Colombie", "Mexique"] },
    { id: 17, tier: 'A', multBytes: 1.1, avSpeed: 1.2, countries: ["Uruguay", "Argentine", "Pérou"] },
    { id: 18, tier: 'A', multBytes: 1.12, avSpeed: 1.2, countries: ["Chine", "Indonésie", "Viêt Nam"] },
    { id: 19, tier: 'A', multBytes: 1.15, avSpeed: 1.2, countries: ["Thaïlande", "Philippines", "Malaisie (Bornéo)"] },
    { id: 20, tier: 'A', multBytes: 1.2, avSpeed: 1.2, countries: ["Kazakhstan", "Ouzbékistan", "Azerbaïdjan"] },
    // TIER B
    { id: 21, tier: 'B', multBytes: 1.3, avSpeed: 1.0, countries: ["Maroc", "Tunisie", "Algérie"] },
    { id: 22, tier: 'B', multBytes: 1.33, avSpeed: 1.0, countries: ["Afrique du Sud", "Kenya", "Nigeria"] },
    { id: 23, tier: 'B', multBytes: 1.37, avSpeed: 1.0, countries: ["Ghana", "Côte d'Ivoire", "Sénégal"] },
    { id: 24, tier: 'B', multBytes: 1.4, avSpeed: 1.0, countries: ["Jordanie", "Koweït", "Liban"] },
    { id: 25, tier: 'B', multBytes: 1.44, avSpeed: 1.0, countries: ["Géorgie", "Arménie", "Moldavie"] },
    { id: 26, tier: 'B', multBytes: 1.48, avSpeed: 1.0, countries: ["Serbie", "Bosnie-Herzégovine", "Monténégro"] },
    { id: 27, tier: 'B', multBytes: 1.51, avSpeed: 1.0, countries: ["Macédoine du Nord", "Albanie", "Kosovo"] },
    { id: 28, tier: 'B', multBytes: 1.55, avSpeed: 1.0, countries: ["Ukraine", "Biélorussie", "Russie"] },
    { id: 29, tier: 'B', multBytes: 1.58, avSpeed: 1.0, countries: ["Équateur", "Paraguay", "Bolivie"] },
    { id: 30, tier: 'B', multBytes: 1.62, avSpeed: 1.0, countries: ["Costa Rica", "Panama", "République Dominicaine"] },
    { id: 31, tier: 'B', multBytes: 1.66, avSpeed: 1.0, countries: ["Jamaïque", "Trinité-et-Tobago", "Barbade"] },
    { id: 32, tier: 'B', multBytes: 1.7, avSpeed: 1.0, countries: ["Maurice", "Seychelles", "Cap-Vert"] },
    { id: 33, tier: 'B', multBytes: 1.73, avSpeed: 1.0, countries: ["Sri Lanka", "Bangladesh", "Népal"] },
    { id: 34, tier: 'B', multBytes: 1.77, avSpeed: 1.0, countries: ["Mongolie", "Kirghizistan", "Tadjikistan"] },
    { id: 35, tier: 'B', multBytes: 1.81, avSpeed: 1.0, countries: ["Brunei", "Laos", "Cambodge"] },
    { id: 36, tier: 'B', multBytes: 1.85, avSpeed: 1.0, countries: ["Oman (Sud)", "Yémen", "Irak"] },
    { id: 37, tier: 'B', multBytes: 1.88, avSpeed: 1.0, countries: ["Zimbabwe", "Zambie", "Namibie"] },
    { id: 38, tier: 'B', multBytes: 1.92, avSpeed: 1.0, countries: ["Botswana", "Rwanda", "Ouganda"] },
    { id: 39, tier: 'B', multBytes: 1.96, avSpeed: 1.0, countries: ["Tanzanie", "Mozambique", "Angola"] },
    { id: 40, tier: 'B', multBytes: 2.0, avSpeed: 1.0, countries: ["Gabon", "Cameroun", "République du Congo"] },
    // TIER C
    { id: 41, tier: 'C', multBytes: 2.1, avSpeed: 0.8, countries: ["Guatemala", "Honduras", "El Salvador"] },
    { id: 42, tier: 'C', multBytes: 2.2, avSpeed: 0.8, countries: ["Nicaragua", "Belize", "Guyana"] },
    { id: 43, tier: 'C', multBytes: 2.3, avSpeed: 0.8, countries: ["Suriname", "Haïti", "Cuba"] },
    { id: 44, tier: 'C', multBytes: 2.4, avSpeed: 0.8, countries: ["Bahamas", "Grenade", "Sainte-Lucie"] },
    { id: 45, tier: 'C', multBytes: 2.5, avSpeed: 0.8, countries: ["Saint-Vincent-et-les-Grenadines", "Antigua-et-Barbuda", "Saint-Kitts-et-Nevis"] },
    { id: 46, tier: 'C', multBytes: 2.6, avSpeed: 0.8, countries: ["Dominique", "Fidji", "Vanuatu"] },
    { id: 47, tier: 'C', multBytes: 2.7, avSpeed: 0.8, countries: ["Samoa", "Tonga", "Kiribati"] },
    { id: 48, tier: 'C', multBytes: 2.8, avSpeed: 0.8, countries: ["Micronésie", "Palaos", "Îles Marshall"] },
    { id: 49, tier: 'C', multBytes: 2.9, avSpeed: 0.8, countries: ["Tuvalu", "Nauru", "Îles Salomon"] },
    { id: 50, tier: 'C', multBytes: 3.0, avSpeed: 0.8, countries: ["Timor oriental", "Papouasie-Nouvelle-Guinée", "Maldives"] },
    { id: 51, tier: 'C', multBytes: 3.1, avSpeed: 0.8, countries: ["Bhoutan", "Afghanistan", "Turkménistan"] },
    { id: 52, tier: 'C', multBytes: 3.2, avSpeed: 0.8, countries: ["Syrie", "Palestine", "Corée du Nord"] },
    { id: 53, tier: 'C', multBytes: 3.3, avSpeed: 0.8, countries: ["Madagascar", "Malawi", "Éthiopie"] },
    { id: 54, tier: 'C', multBytes: 3.4, avSpeed: 0.8, countries: ["Soudan", "Soudan du Sud", "Érythrée"] },
    { id: 55, tier: 'C', multBytes: 3.5, avSpeed: 0.8, countries: ["Somalie", "Djibouti", "Mauritanie"] },
    // TIER D
    { id: 56, tier: 'D', multBytes: 3.6, avSpeed: 0.5, countries: ["Tchad", "Niger", "Mali", "Burkina Faso"] },
    { id: 57, tier: 'D', multBytes: 3.8, avSpeed: 0.5, countries: ["Guinée", "Guinée-Bissau", "Sierra Leone", "Liberia"] },
    { id: 58, tier: 'D', multBytes: 4.0, avSpeed: 0.5, countries: ["Togo", "Bénin", "République Centrafricaine", "RDC"] },
    { id: 59, tier: 'D', multBytes: 4.2, avSpeed: 0.5, countries: ["Burundi", "Comores", "Guinée équatoriale", "Sao Tomé-et-Principe"] },
    { id: 60, tier: 'D', multBytes: 4.4, avSpeed: 0.5, countries: ["Lesotho", "Eswatini", "Libye", "Vatican"] },
    { id: 61, tier: 'D', multBytes: 4.6, avSpeed: 0.5, countries: ["Saint-Marin", "Monaco", "Liechtenstein", "Andorre"] },
    { id: 62, tier: 'D', multBytes: 4.8, avSpeed: 0.5, countries: ["Nauru (Secteur B)", "Tuvalu (Atolls)", "Niue", "Îles Cook"] },
    { id: 63, tier: 'D', multBytes: 5.0, avSpeed: 0.5, countries: ["Micronésie (Sud)", "Kiribati (Est)", "Somalie (Nord)", "Yémen (Est)"] }
];